#!/bin/bash

SRC=src
OUT=out
BROWSERIFY=node_modules/browserify/bin/cmd.js

rm -rf $OUT
mkdir -p $OUT

$BROWSERIFY -o $OUT/index.bundle.js $SRC/index.js

cp index.html $OUT/index.html
cp css/*.css $OUT
